### ISSUE TITLE
Error: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by grendon** [ulelab/ultraplex#30]
I am trying to run ultraplex 1.2.4  (python 3.7.2) on my cluster and I get this error.

The cmd:

<pre>
ultraplex -b samplesheet_ultraplex_tiny.csv \
-i   Pool_1_TAATACAG-ATATTCAC_L001_R1_001.fastq.gz \
-i2  Pool_1_TAATACAG-ATATTCAC_L001_R2_001.fastq.gz \
-d   $PWD/test_ultraplex_iny_m5_1_m3_0_kbc_dbr \
-kbc -dbr
</pre>

The stdout:

<pre>
Traceback (most recent call last):
  File "/home/apps2/software/Python/3.7.2-IGB-gcc-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 681, in run
    trimmed=trimmed1)
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 768, in remove_mate_adapter
    if len(to_remove) > 0:
TypeError: object of type 'NoneType' has no len()
Process WorkerProcess-2:
Traceback (most recent call last):
  File "/home/apps2/software/Python/3.7.2-IGB-gcc-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 681, in run
    trimmed=trimmed1)
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 768, in remove_mate_adapter
    if len(to_remove) > 0:
TypeError: object of type 'NoneType' has no len()
Process WorkerProcess-3:
Traceback (most recent call last):
  File "/home/apps2/software/Python/3.7.2-IGB-gcc-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 681, in run
    trimmed=trimmed1)
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 768, in remove_mate_adapter
    if len(to_remove) > 0:
TypeError: object of type 'NoneType' has no len()
Process WorkerProcess-4:
Traceback (most recent call last):
  File "/home/apps2/software/Python/3.7.2-IGB-gcc-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 681, in run
    trimmed=trimmed1)
  File "/home/apps2/software/ultraplex/1.2.4-IGB-gcc-8.2.0-Python-3.7.2/lib/python3.7/site-packages/ultraplex/__main__.py", line 768, in remove_mate_adapter
    if len(to_remove) > 0:
TypeError: object of type 'NoneType' has no len()

</pre>

It looks like it is trying to spawn four jobs and then fails.

Could you please tell me how to correct this problem?

[samplesheet_ultraplex_tiny.csv](https://github.com/ulelab/ultraplex/files/7572734/samplesheet_ultraplex_tiny.csv)

**Comment by Delayed-Gitification** [comment]
First, apologies for the delay - I didn't get a notification of this issue so only saw it today (hopefully fixed in my notification settings now!)

I had difficulty replicating the error above with my test data. However, I'm fairly confident that I've fixed this issue in the latest release (v1.2.5). It's on PyPI now - and should be on Bioconda shortly. Do let me know if that works for you.
