### ISSUE TITLE
AssertionError: 5' barcodes not consistent

### ISSUE THREAD

**Issue by akhst7** [ulelab/ultraplex#33]
I run a follwoing;

`ultraplex -i Sample1_S0_L001_R1_001.fastq.gz -b barcode.csv`

and I got a following output with an error;

Namespace(adapter='AGATCGGAAGAGCGGTTCAG', adapter2='AGATCGGAAGAGCGTCGTG', barcodes='barcode.csv', directory='', dont_build_reference=False, final_min_length=20, fiveprimemismatches=1, ignore_no_match=False, ignore_space_warning=False, input_2='', inputfastq='Sample1_S0_L001_R1_001.fastq.gz', keep_barcode=False, min_trim=3, outputprefix='demux', phredquality=30, phredquality_5_prime=0, sbatchcompression=False, threads=4, threeprimemismatches=0, ultra=False)
Traceback (most recent call last):
  File "/usr/local/bin/ultraplex", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ultraplex/__main__.py", line 1375, in main
    five_p_bcs, three_p_bcs, linked_bcds, min_score_5_p, sample_names = process_bcs(barcodes_csv, mismatch_5p)
  File "/usr/local/lib/python3.8/dist-packages/ultraplex/__main__.py", line 1136, in process_bcs
    assert len(comma_split[0].rstrip().upper().replace("N", "").split(":")[
AssertionError: 5' barcodes not consistent

A barcode.csv just has the first column of  the 5' barcode and no 3' barcode. 

Any pointers to what I am missing here is appreciated.

**Comment by Delayed-Gitification** [comment]
Hi, could you please send the barcodes CSV you are using?

**Comment by akhst7** [comment]
@Delayed-Gitification, 

I attached the barcode.csv
[barcode.csv](https://github.com/ulelab/ultraplex/files/8233437/barcode.csv)

Thanks.

**Comment by Delayed-Gitification** [comment]
Hi @akhst7 . I just ran ultraplex (the latest version, 1.2.5) on my machine using your barcode.csv. It ran fine for me with no error regarding the barcodes. 

Perhaps this is due to some kind of program or operating system-specific file encoding? I was running on Ubuntu.

I attach the version I downloaded and ran on ubuntu with no problems.

[barcode (1).csv](https://github.com/ulelab/ultraplex/files/8237614/barcode.1.csv)

**Comment by Delayed-Gitification** [comment]
@akhst7 make sure there is no extra empty lines or spaces anywhere. If using Excel to make the csv, make sure to export as the plain "CSV (Comma delimited) (*.csv)" option

**Comment by akhst7** [comment]
@Delayed-Gitification, it worked.  An original csv I created did too have commas at al. 

Thanks.

**Comment by Erythroxylum** [comment]
Hello, @Delayed-Gitification
I am getting the same error after checking that there are no extra characters anywhere and the .csv is attached. My barcodes are of different lengths, could this cause the problem? 
Thanks for your help.
Dawson

Namespace(adapter='AGATCGGAAGAGCGGTTCAG', adapter2='AGATCGGAAGAGCGTCGTG', barcodes='/home/FM/dwhite/panDryas/barcodes-Ronikier.csv', directory='Ronikier/', fiveprimemismatches=1, ignore_no_match=False, ignore_space_warning=False, input_2='White-Dryas-Jan2024_S414_L005_R2_001.fastq.gz', inputfastq='White-Dryas-Jan2024_S414_L005_R1_001.fastq.gz', min_length=22, min_trim=3, outputprefix='demux', phredquality=30, phredquality_5_prime=0, sbatchcompression=False, threads=4, threeprimemismatches=0, ultra=False)
Traceback (most recent call last):
  File "/home/FM/dwhite/miniconda3/envs/ultra/bin/ultraplex", line 10, in <module>
    sys.exit(main())
  File "/home/FM/dwhite/miniconda3/envs/ultra/lib/python3.6/site-packages/ultraplex/__main__.py", line 1288, in main
    five_p_bcs, three_p_bcs, linked_bcs, min_score_5_p, sample_names = process_bcs(barcodes_csv, mismatch_5p)
  File "/home/FM/dwhite/miniconda3/envs/ultra/lib/python3.6/site-packages/ultraplex/__main__.py", line 1069, in process_bcs
    assert len(comma_split[0].rstrip().upper().replace("N", "").split(":")[0]) == fivelength, "5' barcodes not consistent"
AssertionError: 5' barcodes not consistent
[samples-barcodes.csv](https://github.com/ulelab/ultraplex/files/14539235/samples-barcodes.csv)

**Comment by Delayed-Gitification** [comment]
Yes, would be incompatible sorryOn 8 Mar 2024 14:25, Dawson White ***@***.***> wrote:
Hello, @Delayed-Gitification
I am getting the same error after checking that there are no extra characters anywhere and the .csv is attached. My barcodes are of different lengths, could this cause the problem?
Thanks for your help.
Dawson
Namespace(adapter='AGATCGGAAGAGCGGTTCAG', adapter2='AGATCGGAAGAGCGTCGTG', barcodes='/home/FM/dwhite/panDryas/barcodes-Ronikier.csv', directory='Ronikier/', fiveprimemismatches=1, ignore_no_match=False, ignore_space_warning=False, input_2='White-Dryas-Jan2024_S414_L005_R2_001.fastq.gz', inputfastq='White-Dryas-Jan2024_S414_L005_R1_001.fastq.gz', min_length=22, min_trim=3, outputprefix='demux', phredquality=30, phredquality_5_prime=0, sbatchcompression=False, threads=4, threeprimemismatches=0, ultra=False)
Traceback (most recent call last):
File "/home/FM/dwhite/miniconda3/envs/ultra/bin/ultraplex", line 10, in 
sys.exit(main())
File "/home/FM/dwhite/miniconda3/envs/ultra/lib/python3.6/site-packages/ultraplex/main.py", line 1288, in main
five_p_bcs, three_p_bcs, linked_bcs, min_score_5_p, sample_names = process_bcs(barcodes_csv, mismatch_5p)
File "/home/FM/dwhite/miniconda3/envs/ultra/lib/python3.6/site-packages/ultraplex/main.py", line 1069, in process_bcs
assert len(comma_split[0].rstrip().upper().replace("N", "").split(":")[0]) == fivelength, "5' barcodes not consistent"
AssertionError: 5' barcodes not consistent
samples-barcodes.csv
