### ISSUE TITLE
Problem with running Ultraplex

### ISSUE THREAD

**Issue by lichen-fungus** [ulelab/ultraplex#53]
Hello, 

THanks for developing a potentially incredibly useful tool!

I am new to ultraplex and am trying to run your testdata including barcodes from GitHub. I noticed also that the testdata *.fq.gz seems to contain mainly Ns.  When I run Ultraplex with the test data, it throws this error:

ultraplex -i HAL169A1-A22_S1_L001_R1_001.fastq.gz -b barcodes_ultraplex_format.csv -t 10 -dbr --ignore_no_match

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@   @@@@   .@@   @@@@@@@          @@         @@@@@@    (@@@@@        @@@    @@@@@@@         @@    @@@    @
@@@@   @@@@    @@   ,@@@@@@@@@    @@@@@    @@@   @@@@   (   @@@@   @@@   @@    @@@@@@@   @@@@@@@@@@   #   @@@@
@@@   &@@@    @@    @@@@@@@@@%   @@@@@         @@@@(   @    @@@         @@    @@@@@@@         @@@@@     @@@@@@
@@    @@@    @@    @@@@@@@@@@   @@@@@    @@    @@@          @@   .@@@@@@@*   @@@@@@@    @@@@@@@@.   @    @@@@@
@@@       @@@@.        @@@@@   @@@@@&   @@@.   &   &@@@@    @    @@@@@@@@         @          @    @@@@    @@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Namespace(adapter='AGATCGGAAGAGCACACGTCTGAA', adapter2='AGATCGGAAGAGCGTCGTG', barcodes='barcodes_ultraplex_format.csv', directory='', dont_build_reference=True, final_min_length=20, fiveprimemismatches=0, ignore_no_match=True, ignore_space_warning=False, input_2='', inputfastq='HAL169A1-A22_S1_L001_R1_001.fastq.gz', keep_barcode=False, min_trim=3, outputprefix='demux', phredquality=30, phredquality_5_prime=0, sbatchcompression=False, threads=10, three_prime_only=False, threeprimemismatches=0, tso_seq='', ultra=False)
Demultiplexing...
Process WorkerProcess-1:
Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/ultraplex/__main__.py", line 974, in run
    new_dict = merge_defaultdicts(prev_dict, read_number)
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/ultraplex/__main__.py", line 28, in merge_defaultdicts
    merged[key] += value
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

##########

When I interrupt the program, I get this output: "Demultiplexing complete! 165308 reads processed" (rest below). But there is no output.

###########
Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/ultraplex/bin/ultraplex", line 11, in <module>
    sys.exit(main())
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/ultraplex/__main__.py", line 2068, in main
    reads_samps_Dict = read_number.get()
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/multiprocess/queues.py", line 100, in get
    res = self._recv_bytes()
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/multiprocess/connection.py", line 219, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/multiprocess/connection.py", line 417, in _recv_bytes
    buf = self._recv(4)
  File "/home/admin/anaconda3/envs/ultraplex/lib/python3.8/site-packages/multiprocess/connection.py", line 382, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

##########

Python version: 3.8, installed in its own Anaconda environment. I also tried to install ultraplex in a fresh Anaconda environment using python 3.7 and 3.9; same problem. I tried installing through mamba with different python versions - same problem.

I got the same error when trying my own data for the various ultraplex installs, so it's not just the test dataset.  Now I have no clue how to proceed to get the program to work.
Do you have a suggestion what to do? 

Thank you !!

Below are the package versions in my current ultraplex conda environment, just in case this might help:

# packages in environment at /home/werthadmin/anaconda3/envs/ultraplex:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_2    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
dnaio                     1.2.0            py38he5da3d1_0    bioconda
isa-l                     2.30.0               ha770c72_4    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
multiprocess              0.70.14          py38h0a891b7_3    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.7                h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pbzip2                    1.1.13                        0    conda-forge
pigz                      2.6                  h27826a3_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.8.13          ha86cf86_0_cpython    conda-forge
python-isal               1.1.0            py38h0a891b7_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4            py38h06a4308_0
setuptools_scm            8.0.4                hd3eb1b0_0
sqlite                    3.40.0               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ultraplex                 1.2.9            py38he5da3d1_1    bioconda
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xopen                     1.7.0            py38h578d9bd_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.19.0           py38h0a891b7_0    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

**Comment by jkimsis** [comment]
I have the same problem, I've installed Ultraplex using pip.

**Comment by ANetTow** [comment]
I have this same problem.  I have found that removing the --ignore_no_match option allows the code to run without the TypeError.

**Comment by lichen-fungus** [comment]
Thanks, ANetTow, looks like it's running without this option also on my system! 
I have meanwhile worked with demultiplex by Jeroen F.J. Laros (jfjlaros) which works reliably but it's not fast.
